version: '3.8'

services:

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"      

  web:
    build: .
#    command: python app.py run -h 0.0.0.0
    volumes:
      - ./app
    ports:
      - "5000:5000"
    environment:
      - 'ZIPKIN_DSN=http://51.250.105.11:9411/api/v2/spans'
#    env_file:
#      .
    depends_on:
      - db
        
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=111
      - POSTGRES_DB=testdb
    ports:
      - ${POSTGRES_PORT:-5432}:5432

volumes:
  postgres_data:
